EDERCMS-232: Add Lely fonts and styles
techdivision/eds-eder-main pull request #173
Opened 2024-10-16 13:07 UTC by dmorbitzer

[EDERCMS-232](https://techdivision.atlassian.net/browse/EDERCMS-232)

Test URLs:

- Before: https://main--eds-eder-main--techdivision.aem.live/
- After: https://feature-edercms-232--eds-eder-main--techdivision.aem.live/

2024-10-18 15:14 UTC, sippsolutions requested changes

2024-10-18 15:14 UTC, sippsolutions commented on .multisite/lelycenterinbayern/styles/fonts/ubuntu-bold.woff2
fonts sind doppelt drin

2024-10-18 15:14 UTC, sippsolutions commented on .multisite/lelycenterinbayern/styles/fonts.css
> +  font-family: roboto;
warum roboto?

2024-10-18 15:14 UTC, sippsolutions commented on .multisite/lelycenterinbayern/styles/styles.css
wollen wir wirklich die styles.css überschreiben. würde ich gerne vermeiden

2024-10-21 06:51 UTC, dmorbitzer commented on .multisite/lelycenterinbayern/styles/styles.css
Bin offen für Vorschläge wie ich einzelne Inhalte überschreiben kann

2024-10-21 14:49 UTC, sippsolutions commented on styles/theme.css
> +  /* font vars */
kann man das nicht in eine font-variables.css oder so hauen? dann müsste man diese nur bei lely abändern

2024-10-22 13:29 UTC, merged